title : Marie-Neige Chapel
author :
  name : Marie-Neige Chapel
  email : marieneigecha@gmail.com
  github : mnchapel

baseurl: ""
url: ""

collections:
  publications:
    output: true
    permalink: /publications/:path/
  research_projects:
    output: true
    permalink: /research_projects/:path/
  experiences:
    output: true


defaults:
  - scope:
      path: ""
      type: publications
    values:
      hidden: true
      layout: publication
  - scope:
      path: ""
      type: research_projects
    values:
      hidden: true
      layout: research_project
